# Generated by Django 3.2.6 on 2025-03-18 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='remarks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='home.remark'),
        ),
        migrations.AlterField(
            model_name='projecttimeline',
            name='revised_completion_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
