# Generated by Django 3.2.6 on 2025-03-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttimeline',
            name='revised_completion_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Revised Completion Date'),
        ),
    ]
