# Generated by Django 3.2.6 on 2025-03-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20250318_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttimeline',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttimeline',
            name='total_cost_Incurred_to_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
