# Generated by Django 3.2.6 on 2025-03-24 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_dumprawdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dumprawdata',
            old_name='contractor',
            new_name='project_contractor',
        ),
    ]
