# Generated by Django 3.2.6 on 2025-03-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_addprojecthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='addprojecthistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='addprojecthistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
